browser:
  browserName: chrome
  headlessBrowser: false
  webElementTimeOut: 15

environment:
  test1:
    active: true
    envName: test1
    appUrl: http://automationpractice.com/
    eTitle: Selenium
  test2:
    active: false
    envName: test2
    appUrl: http://automationpractice.com/
    eTitle: Selenium
