browser:
  browserName: chrome
  headlessBrowser: false
  webElementTimeOut: 20

environment:
  test1:
    active: true
    envName: test1
    appUrl: http://automationpractice.com/
    eTitle: My Store
  test2:
    active: false
    envName: test2
    appUrl: http://automationpractice.com/
    eTitle: My Store
